services:

  ############################################
  # FRONTEND
  ############################################
  fava:
    image: fava
    build:
      context: ./fava
      dockerfile: docker/Dockerfile
    ports:
      - ${FAVA_EXTERNAL_PORT}:5000
    volumes:
      - ./data/${LOCAL_BEANCOUNT_FILE_NAME}:/data/budget.beancount:rw
    command: fava --host 0.0.0.0 --port 5000 --poll-watcher /data/budget.beancount
    restart: unless-stopped

  ############################################
  # BACKEND
  ############################################
  brain:
    image: brain
    build:
      context: ./brain
      dockerfile: docker/Dockerfile
    ports:
      - "${BRAIN_EXTERNAL_PORT}:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./brain:/app
      - ./data:/data
      - ./data/${LOCAL_BEANCOUNT_FILE_NAME}:/data/budget.beancount:rw
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
  

  ############################################
  # BACKUP
  ############################################
  backup:
    build:
      context: ./backup
      dockerfile: docker/Dockerfile
    volumes:
      - ./backup:/app
      - ./data:/data
      - ./data/${LOCAL_BEANCOUNT_FILE_NAME}:/data/budget.beancount:rw
      - ~/.config/rclone:/root/.config/rclone
